# Generated by Django 5.0.8 on 2024-08-12 16:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_remove_teacherprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LinkRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='api_linkreq_timesta_0de2e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='LinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('anchor_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=50)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.advertiserprofile')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_requests', to='api.linkrequeststatus')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_payment_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.linkrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.advertiserprofile')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.publisherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.advertiserprofile')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.publisherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('domain_authority', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('organic_traffic', models.PositiveIntegerField()),
                ('price_per_link', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_slots', models.PositiveIntegerField()),
                ('guidelines', models.TextField()),
                ('support_casino', models.BooleanField(default=False)),
                ('support_sports_betting', models.BooleanField(default=False)),
                ('support_loans', models.BooleanField(default=False)),
                ('support_dating', models.BooleanField(default=False)),
                ('support_forex', models.BooleanField(default=False)),
                ('support_crypto', models.BooleanField(default=False)),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.niche')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.publisherprofile')),
            ],
        ),
        migrations.AddField(
            model_name='linkrequest',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.site'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['domain'], name='api_site_domain_9ca7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['niche'], name='api_site_niche_i_d6cd20_idx'),
        ),
        migrations.AddIndex(
            model_name='linkrequest',
            index=models.Index(fields=['status'], name='api_linkreq_status__bea02d_idx'),
        ),
        migrations.AddIndex(
            model_name='linkrequest',
            index=models.Index(fields=['created_at'], name='api_linkreq_created_430f02_idx'),
        ),
    ]
