# Generated by Django 5.0.8 on 2024-08-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='available_slots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='guidelines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
