# Generated by Django 5.0.8 on 2024-08-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_property_accepts_pets_property_accepts_smokers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
