# Generated by Django 5.0.8 on 2024-08-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
