# Generated by Django 5.0.8 on 2024-08-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_houselocation_housetype_property_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselocation',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='houselocation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
