# Generated by Django 5.0.8 on 2024-09-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_houselocation_city_alter_houselocation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='garden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pool',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
