# Generated by Django 5.0.8 on 2024-09-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_tenantprofile_profile_image'),
        ('api', '0013_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_comments', to='accounts.tenantprofile'),
        ),
    ]
