# Generated by Django 5.0.8 on 2024-10-01 03:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_comment_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tenants_with_access',
            field=models.ManyToManyField(blank=True, related_name='properties_with_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
