# Generated by Django 5.0.8 on 2024-10-20 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='previous_tenants',
            field=models.ManyToManyField(blank=True, null=True, related_name='previous_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='previous_tenants_with_access',
            field=models.ManyToManyField(blank=True, null=True, related_name='previous_tenants_with_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
