# Generated by Django 5.0.8 on 2024-10-23 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_property_previous_tenants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='api_comment_tenant__4ae6d5_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tenant',
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='previous_tenants',
            field=models.ManyToManyField(blank=True, related_name='previous_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='previous_tenants_with_access',
            field=models.ManyToManyField(blank=True, related_name='previous_properties_with_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['commenter'], name='api_comment_comment_d67a97_idx'),
        ),
    ]
