# Generated by Django 5.0.8 on 2024-11-23 10:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_property_accepts_cash_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='affidavit',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
        migrations.AddField(
            model_name='property',
            name='proof_of_residence',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
