# Generated by Django 5.0.8 on 2025-01-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_comment_api_comment_propert_662b10_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ai_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
