# Generated by Django 5.0.8 on 2025-01-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_comment_ai_rating_comment_is_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='overall_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
