# Generated by Django 4.0.6 on 2025-02-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_leasedocumentpayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_borehole',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_solar_power',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
