# Generated by Django 5.0.8 on 2024-08-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_publisherprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='accepts_pets',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='accepts_smokers',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='handles_own_maintenance',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='is_profile_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='pet_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='preferred_contractors',
            field=models.TextField(blank=True, help_text='List of preferred contractors with contact info', null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='preferred_lease_term',
            field=models.IntegerField(blank=True, help_text='Preferred lease term in months', null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='required_documents',
            field=models.TextField(blank=True, help_text='List of required documents from tenants', null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='screening_criteria',
            field=models.TextField(blank=True, help_text='Describe tenant screening criteria', null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='criminal_record',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='employer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='has_vehicle',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='is_profile_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='max_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='num_of_vehicles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='number_of_occupants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='personal_reference_1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='personal_reference_1_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='personal_reference_1_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='personal_reference_2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='personal_reference_2_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='personal_reference_2_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='pet_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='pets',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='preferred_area',
            field=models.TextField(blank=True, help_text='Comma-separated list of preferred areas', null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='preferred_lease_term',
            field=models.IntegerField(blank=True, help_text='Preferred lease term in months', null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='preferred_move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='smoker',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='work_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
