# Generated by Django 5.0.8 on 2024-08-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_landlordprofile_accepts_pets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordprofile',
            name='accepts_pets',
        ),
        migrations.RemoveField(
            model_name='landlordprofile',
            name='accepts_smokers',
        ),
        migrations.RemoveField(
            model_name='landlordprofile',
            name='pet_deposit',
        ),
        migrations.RemoveField(
            model_name='landlordprofile',
            name='preferred_lease_term',
        ),
    ]
