# Generated by Django 5.0.8 on 2024-08-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_landlordprofile_accepts_pets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordprofile',
            name='handles_own_maintenance',
        ),
        migrations.RemoveField(
            model_name='landlordprofile',
            name='preferred_contractors',
        ),
        migrations.RemoveField(
            model_name='landlordprofile',
            name='required_documents',
        ),
        migrations.RemoveField(
            model_name='landlordprofile',
            name='screening_criteria',
        ),
    ]
