# Generated by Django 5.0.8 on 2024-09-10 04:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_tenantprofile_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to),
        ),
    ]
