# Generated by Django 5.0.8 on 2024-09-19 03:51

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_pricingtier_tenantprofile_num_properties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='id_image',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.upload_to),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='proof_of_residence',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.upload_to),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='proof_of_employment',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.upload_to),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='id_image',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.upload_to),
        ),
    ]
