# Generated by Django 5.0.8 on 2024-09-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_payment_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='subscription_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
