# Generated by Django 5.0.8 on 2024-12-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_landlordprofile_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='next_of_kin_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='next_of_kin_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
