# Generated by Django 5.0.8 on 2025-01-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_tenantprofile_next_of_kin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='current_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='current_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
    ]
