# Generated by Django 5.0.8 on 2025-01-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_tenantrating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenantrating',
            unique_together={('tenant', 'landlord')},
        ),
    ]
