# Generated by Django 5.0.8 on 2025-02-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_tenantrating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
